create database shopping_db;
use shopping_db;

select * from shopping_behavior;

select * from shopping_behavior limit 5;




#--Q1. What is the total revenue generated by male vs. female customers?


select gender, sum(purchase_amount) as revenue from shopping_behavior group by gender;


# --Q2. Which customers used a discount but still spent more than the average purchase amount?

select customer_id,purchase_amount from shopping_behavior where discount_applied = 'yes' and purchase_amount >= (select avg(purchase_amount) from shopping_behavior);

select avg(purchase_amount) from shopping_behavior;



# -- Q3. Which are the top 5 products with the highest average review rating?

select item_purchased,round(avg(review_rating)) from shopping_behavior group by item_purchased order by avg(review_rating) desc limit 5;

select * from shopping_behavior;

# --Q4. Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type, avg(purchase_amount) from shopping_behavior where shipping_type in ("standard","express") group by shipping_type;



# --Q5. Do subscribed customers spend more? Compare average spend and total revenue

select subscription_status,
count(customer_id) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from shopping_behavior
group by subscription_status
order by total_revenue, avg_spend desc;

# --Q6. Which 5 products have the highest percentage of purchases with discounts applied?

select item_purchased,
round(100 * sum(case when discount_applied = 'yes' then 1 else 0 end) / count(*),2) as discount_rate
from shopping_behavior
group by item_purchased
order by discount_rate desc
limit 5;


# --Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment. 

with customer_type as (
select customer_id, previous_purchases,
case 
    when previous_purchases = 1 then 'New'
    when previous_purchases between 2 and 10 then 'returning'
    else 'loyal'
    end as customer_segment
from shopping_behavior)

select customer_segment, count(*) as 'Number of Customers'
from customer_type
group by customer_segment;

# --Q8. What are the top 3 most purchased products within each category?

WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM shopping_behavior
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
# --Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM shopping_behavior
WHERE previous_purchases > 5
GROUP BY subscription_status;

# create age group column and 
# --Q10. What is the revenue contribution of each age group?

SELECT 
    CASE 
        WHEN age <= 25 THEN 'Young_Adult'
        WHEN age <= 35 THEN 'Adult'
        WHEN age <= 50 THEN 'Middle-aged'
        ELSE 'Senior'
    END AS age_group,
    
    SUM(purchase_amount) AS total_revenue

FROM shopping_behavior

GROUP BY age_group
ORDER BY total_revenue DESC;
